/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#undef HAVE_ACCEPT4

#define HAVE_BROKEN_MSG_CMSG_CLOEXEC 0

#undef HAVE_MEMFD_CREATE

#define HAVE_MKOSTEMP

#undef HAVE_MREMAP

#define HAVE_POSIX_FALLOCATE

#undef HAVE_PRCTL

#define HAVE_STRNDUP

#undef HAVE_SYS_PRCTL_H

#undef HAVE_SYS_PROCCTL_H

#define HAVE_SYS_UCRED_H

#define HAVE_XUCRED_CR_PID 0

#define PACKAGE "wayland"

#define PACKAGE_VERSION "1.23.1"

